### PR TITLE
update foreground color in BRACE_ATTR_GUTTER

### PR DESCRIPTION
**Pull request by rala72**
background and foreground color was the same

### CODE REVIEW

**Comment by rala72** [comment]
interesting
the preview looked different but if it is the case feel free to do so and close this PR

**Comment by AprilViolet** [comment]
Yes, BRACE_ATTR_GUTTER affects the color of the parentheses on the left, the background color is useless here, at least I set it outless here.You can try it

**Comment by rala72** [comment]
ah, I know I understand what the color is about 🤦‍♂️
so this removing would be the best option
this PR can be closed then

therefore, I now understand what it is about, is it possible to move `Other settings > HighlightBracketPair > Open reder bracket in gutter` to `Editor > General > Gutter Icons`?
I think this would be better as issue

**Comment by AprilViolet** [comment]
Yes, according to the function, it is more appropriate to put it under gutter icons, but the plugin has other settings at present or in the future. Maybe it is more appropriate to put it together, so that users can configure it in one place.

**Pull request closed without merging**
